#pragma once
// Autogenerated - do not edit
typedef int (*bl_entity_hurt_t)(Entity*, EntityDamageSource const&, int);
static bl_entity_hurt_t bl__ZTV10CaveSpider_hurt_real,bl__ZTV10ItemEntity_hurt_real,bl__ZTV10Silverfish_hurt_real,bl__ZTV11FishingHook_hurt_real,bl__ZTV11LocalPlayer_hurt_real,bl__ZTV11MinecartTNT_hurt_real,bl__ZTV11MushroomCow_hurt_real,bl__ZTV11WaterAnimal_hurt_real,bl__ZTV12FallingBlock_hurt_real,bl__ZTV12RemotePlayer_hurt_real,bl__ZTV12ServerPlayer_hurt_real,bl__ZTV12ThrownPotion_hurt_real,bl__ZTV12TripodCamera_hurt_real,bl__ZTV13ExperienceOrb_hurt_real,bl__ZTV13HangingEntity_hurt_real,bl__ZTV13LargeFireball_hurt_real,bl__ZTV13LightningBolt_hurt_real,bl__ZTV13MinecartChest_hurt_real,bl__ZTV13PathfinderMob_hurt_real,bl__ZTV13SmallFireball_hurt_real,bl__ZTV13TamableAnimal_hurt_real,bl__ZTV14MinecartHopper_hurt_real,bl__ZTV14ZombieVillager_hurt_real,bl__ZTV15AmbientCreature_hurt_real,bl__ZTV15HumanoidMonster_hurt_real,bl__ZTV16ExperiencePotion_hurt_real,bl__ZTV16MinecartRideable_hurt_real,bl__ZTV16ThrownEnderpearl_hurt_real,bl__ZTV3Bat_hurt_real,bl__ZTV3Cow_hurt_real,bl__ZTV3Mob_hurt_real,bl__ZTV3Pig_hurt_real,bl__ZTV4Boat_hurt_real,bl__ZTV4Wolf_hurt_real,bl__ZTV5Arrow_hurt_real,bl__ZTV5Blaze_hurt_real,bl__ZTV5Ghast_hurt_real,bl__ZTV5Golem_hurt_real,bl__ZTV5Sheep_hurt_real,bl__ZTV5Slime_hurt_real,bl__ZTV5Squid_hurt_real,bl__ZTV5Witch_hurt_real,bl__ZTV6Animal_hurt_real,bl__ZTV6Entity_hurt_real,bl__ZTV6Ocelot_hurt_real,bl__ZTV6Player_hurt_real,bl__ZTV6Rabbit_hurt_real,bl__ZTV6Spider_hurt_real,bl__ZTV6Zombie_hurt_real,bl__ZTV7Chicken_hurt_real,bl__ZTV7Creeper_hurt_real,bl__ZTV7Monster_hurt_real,bl__ZTV8EnderMan_hurt_real,bl__ZTV8Fireball_hurt_real,bl__ZTV8Minecart_hurt_real,bl__ZTV8Painting_hurt_real,bl__ZTV8Skeleton_hurt_real,bl__ZTV8Snowball_hurt_real,bl__ZTV8Villager_hurt_real,bl__ZTV9AgableMob_hurt_real,bl__ZTV9IronGolem_hurt_real,bl__ZTV9LavaSlime_hurt_real,bl__ZTV9PigZombie_hurt_real,bl__ZTV9PrimedTnt_hurt_real,bl__ZTV9SnowGolem_hurt_real,bl__ZTV9Throwable_hurt_real,bl__ZTV9ThrownEgg_hurt_real;
static int bl__ZTV10CaveSpider_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV10CaveSpider_hurt_real(entity, damage, hearts);
}
static int bl__ZTV10ItemEntity_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV10ItemEntity_hurt_real(entity, damage, hearts);
}
static int bl__ZTV10Silverfish_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV10Silverfish_hurt_real(entity, damage, hearts);
}
static int bl__ZTV11FishingHook_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV11FishingHook_hurt_real(entity, damage, hearts);
}
static int bl__ZTV11LocalPlayer_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV11LocalPlayer_hurt_real(entity, damage, hearts);
}
static int bl__ZTV11MinecartTNT_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV11MinecartTNT_hurt_real(entity, damage, hearts);
}
static int bl__ZTV11MushroomCow_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV11MushroomCow_hurt_real(entity, damage, hearts);
}
static int bl__ZTV11WaterAnimal_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV11WaterAnimal_hurt_real(entity, damage, hearts);
}
static int bl__ZTV12FallingBlock_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV12FallingBlock_hurt_real(entity, damage, hearts);
}
static int bl__ZTV12RemotePlayer_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV12RemotePlayer_hurt_real(entity, damage, hearts);
}
static int bl__ZTV12ServerPlayer_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV12ServerPlayer_hurt_real(entity, damage, hearts);
}
static int bl__ZTV12ThrownPotion_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV12ThrownPotion_hurt_real(entity, damage, hearts);
}
static int bl__ZTV12TripodCamera_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV12TripodCamera_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13ExperienceOrb_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13ExperienceOrb_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13HangingEntity_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13HangingEntity_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13LargeFireball_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13LargeFireball_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13LightningBolt_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13LightningBolt_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13MinecartChest_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13MinecartChest_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13PathfinderMob_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13PathfinderMob_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13SmallFireball_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13SmallFireball_hurt_real(entity, damage, hearts);
}
static int bl__ZTV13TamableAnimal_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV13TamableAnimal_hurt_real(entity, damage, hearts);
}
static int bl__ZTV14MinecartHopper_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV14MinecartHopper_hurt_real(entity, damage, hearts);
}
static int bl__ZTV14ZombieVillager_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV14ZombieVillager_hurt_real(entity, damage, hearts);
}
static int bl__ZTV15AmbientCreature_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV15AmbientCreature_hurt_real(entity, damage, hearts);
}
static int bl__ZTV15HumanoidMonster_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV15HumanoidMonster_hurt_real(entity, damage, hearts);
}
static int bl__ZTV16ExperiencePotion_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV16ExperiencePotion_hurt_real(entity, damage, hearts);
}
static int bl__ZTV16MinecartRideable_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV16MinecartRideable_hurt_real(entity, damage, hearts);
}
static int bl__ZTV16ThrownEnderpearl_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV16ThrownEnderpearl_hurt_real(entity, damage, hearts);
}
static int bl__ZTV3Bat_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV3Bat_hurt_real(entity, damage, hearts);
}
static int bl__ZTV3Cow_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV3Cow_hurt_real(entity, damage, hearts);
}
static int bl__ZTV3Mob_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV3Mob_hurt_real(entity, damage, hearts);
}
static int bl__ZTV3Pig_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV3Pig_hurt_real(entity, damage, hearts);
}
static int bl__ZTV4Boat_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV4Boat_hurt_real(entity, damage, hearts);
}
static int bl__ZTV4Wolf_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV4Wolf_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Arrow_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Arrow_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Blaze_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Blaze_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Ghast_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Ghast_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Golem_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Golem_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Sheep_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Sheep_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Slime_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Slime_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Squid_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Squid_hurt_real(entity, damage, hearts);
}
static int bl__ZTV5Witch_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV5Witch_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Animal_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Animal_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Entity_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Entity_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Ocelot_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Ocelot_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Player_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Player_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Rabbit_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Rabbit_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Spider_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Spider_hurt_real(entity, damage, hearts);
}
static int bl__ZTV6Zombie_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV6Zombie_hurt_real(entity, damage, hearts);
}
static int bl__ZTV7Chicken_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV7Chicken_hurt_real(entity, damage, hearts);
}
static int bl__ZTV7Creeper_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV7Creeper_hurt_real(entity, damage, hearts);
}
static int bl__ZTV7Monster_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV7Monster_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8EnderMan_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8EnderMan_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Fireball_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Fireball_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Minecart_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Minecart_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Painting_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Painting_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Skeleton_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Skeleton_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Snowball_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Snowball_hurt_real(entity, damage, hearts);
}
static int bl__ZTV8Villager_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV8Villager_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9AgableMob_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9AgableMob_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9IronGolem_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9IronGolem_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9LavaSlime_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9LavaSlime_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9PigZombie_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9PigZombie_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9PrimedTnt_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9PrimedTnt_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9SnowGolem_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9SnowGolem_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9Throwable_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9Throwable_hurt_real(entity, damage, hearts);
}
static int bl__ZTV9ThrownEgg_hurt_hook(Entity* entity, EntityDamageSource const& damage, int hearts) {
	return bl_Entity_hurt_report(entity, damage, hearts)? 0: bl__ZTV9ThrownEgg_hurt_real(entity, damage, hearts);
}
static void bl_entity_hurt_hook_init(soinfo2* mcpelibhandle) {
	void** vtable;
	int h = vtable_indexes.entity_hurt;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV10CaveSpider");
	bl__ZTV10CaveSpider_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV10CaveSpider_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV10ItemEntity");
	bl__ZTV10ItemEntity_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV10ItemEntity_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV10Silverfish");
	bl__ZTV10Silverfish_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV10Silverfish_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV11FishingHook");
	bl__ZTV11FishingHook_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV11FishingHook_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV11LocalPlayer");
	bl__ZTV11LocalPlayer_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV11LocalPlayer_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV11MinecartTNT");
	bl__ZTV11MinecartTNT_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV11MinecartTNT_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV11MushroomCow");
	bl__ZTV11MushroomCow_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV11MushroomCow_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV11WaterAnimal");
	bl__ZTV11WaterAnimal_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV11WaterAnimal_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV12FallingBlock");
	bl__ZTV12FallingBlock_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV12FallingBlock_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV12RemotePlayer");
	bl__ZTV12RemotePlayer_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV12RemotePlayer_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV12ServerPlayer");
	bl__ZTV12ServerPlayer_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV12ServerPlayer_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV12ThrownPotion");
	bl__ZTV12ThrownPotion_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV12ThrownPotion_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV12TripodCamera");
	bl__ZTV12TripodCamera_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV12TripodCamera_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13ExperienceOrb");
	bl__ZTV13ExperienceOrb_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13ExperienceOrb_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13HangingEntity");
	bl__ZTV13HangingEntity_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13HangingEntity_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13LargeFireball");
	bl__ZTV13LargeFireball_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13LargeFireball_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13LightningBolt");
	bl__ZTV13LightningBolt_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13LightningBolt_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13MinecartChest");
	bl__ZTV13MinecartChest_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13MinecartChest_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13PathfinderMob");
	bl__ZTV13PathfinderMob_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13PathfinderMob_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13SmallFireball");
	bl__ZTV13SmallFireball_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13SmallFireball_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV13TamableAnimal");
	bl__ZTV13TamableAnimal_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV13TamableAnimal_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV14MinecartHopper");
	bl__ZTV14MinecartHopper_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV14MinecartHopper_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV14ZombieVillager");
	bl__ZTV14ZombieVillager_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV14ZombieVillager_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV15AmbientCreature");
	bl__ZTV15AmbientCreature_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV15AmbientCreature_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV15HumanoidMonster");
	bl__ZTV15HumanoidMonster_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV15HumanoidMonster_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV16ExperiencePotion");
	bl__ZTV16ExperiencePotion_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV16ExperiencePotion_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV16MinecartRideable");
	bl__ZTV16MinecartRideable_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV16MinecartRideable_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV16ThrownEnderpearl");
	bl__ZTV16ThrownEnderpearl_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV16ThrownEnderpearl_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV3Bat");
	bl__ZTV3Bat_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV3Bat_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV3Cow");
	bl__ZTV3Cow_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV3Cow_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV3Mob");
	bl__ZTV3Mob_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV3Mob_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV3Pig");
	bl__ZTV3Pig_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV3Pig_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV4Boat");
	bl__ZTV4Boat_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV4Boat_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV4Wolf");
	bl__ZTV4Wolf_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV4Wolf_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Arrow");
	bl__ZTV5Arrow_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Arrow_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Blaze");
	bl__ZTV5Blaze_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Blaze_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Ghast");
	bl__ZTV5Ghast_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Ghast_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Golem");
	bl__ZTV5Golem_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Golem_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Sheep");
	bl__ZTV5Sheep_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Sheep_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Slime");
	bl__ZTV5Slime_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Slime_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Squid");
	bl__ZTV5Squid_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Squid_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV5Witch");
	bl__ZTV5Witch_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV5Witch_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Animal");
	bl__ZTV6Animal_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Animal_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Entity");
	bl__ZTV6Entity_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Entity_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Ocelot");
	bl__ZTV6Ocelot_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Ocelot_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Player");
	bl__ZTV6Player_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Player_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Rabbit");
	bl__ZTV6Rabbit_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Rabbit_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Spider");
	bl__ZTV6Spider_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Spider_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV6Zombie");
	bl__ZTV6Zombie_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV6Zombie_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV7Chicken");
	bl__ZTV7Chicken_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV7Chicken_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV7Creeper");
	bl__ZTV7Creeper_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV7Creeper_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV7Monster");
	bl__ZTV7Monster_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV7Monster_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8EnderMan");
	bl__ZTV8EnderMan_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8EnderMan_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Fireball");
	bl__ZTV8Fireball_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Fireball_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Minecart");
	bl__ZTV8Minecart_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Minecart_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Painting");
	bl__ZTV8Painting_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Painting_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Skeleton");
	bl__ZTV8Skeleton_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Skeleton_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Snowball");
	bl__ZTV8Snowball_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Snowball_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV8Villager");
	bl__ZTV8Villager_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV8Villager_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9AgableMob");
	bl__ZTV9AgableMob_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9AgableMob_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9IronGolem");
	bl__ZTV9IronGolem_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9IronGolem_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9LavaSlime");
	bl__ZTV9LavaSlime_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9LavaSlime_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9PigZombie");
	bl__ZTV9PigZombie_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9PigZombie_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9PrimedTnt");
	bl__ZTV9PrimedTnt_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9PrimedTnt_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9SnowGolem");
	bl__ZTV9SnowGolem_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9SnowGolem_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9Throwable");
	bl__ZTV9Throwable_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9Throwable_hurt_hook;
	vtable = (void**) dobby_dlsym(mcpelibhandle, "_ZTV9ThrownEgg");
	bl__ZTV9ThrownEgg_hurt_real = (bl_entity_hurt_t) vtable[h];
	vtable[h] = (void*) &bl__ZTV9ThrownEgg_hurt_hook;
}
