/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
#define _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeModelAddBox
 * Signature: (ILjava/lang/String;FFFIIIFIIZFF)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeModelAddBox
  (JNIEnv *, jclass, jint, jstring, jfloat, jfloat, jfloat, jint, jint, jint, jfloat, jint, jint, jboolean, jfloat, jfloat);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeModelClear
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeModelClear
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeModelPartExists
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeModelPartExists
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeCreateHumanoidRenderer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeCreateHumanoidRenderer
  (JNIEnv *, jclass);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeCreateItemSpriteRenderer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeCreateItemSpriteRenderer
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager
 * Method:    nativeModelSetRotationPoint
 * Signature: (ILjava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_nativeModelSetRotationPoint
  (JNIEnv *, jclass, jint, jstring, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModelPart */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModelPart
#define _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModelPart
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModel */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModel
#define _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeModel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRenderer */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRenderer
#define _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi
#define _Included_net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi
#ifdef __cplusplus
extern "C" {
#endif
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_serialVersionUID
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_serialVersionUID 2829861078851942586LL
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_EMPTY
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_EMPTY 0L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_READONLY
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_READONLY 1L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_DONTENUM
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_DONTENUM 2L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_PERMANENT
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_PERMANENT 4L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_UNINITIALIZED_CONST
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_UNINITIALIZED_CONST 8L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_CONST
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_CONST 13L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_QUERY
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_QUERY 1L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY 2L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY_CONST
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY_CONST 3L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY_GETTER_SETTER
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_MODIFY_GETTER_SETTER 4L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_CONVERT_ACCESSOR_TO_DATA
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_SLOT_CONVERT_ACCESSOR_TO_DATA 5L
#undef net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_INITIAL_SLOT_SIZE
#define net_zhuoweizhang_mcpelauncher_api_modpe_RendererManager_NativeRendererApi_INITIAL_SLOT_SIZE 4L
#ifdef __cplusplus
}
#endif
#endif
