/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zhuoweizhang_mcpelauncher_ScriptManager */

#ifndef _Included_net_zhuoweizhang_mcpelauncher_ScriptManager
#define _Included_net_zhuoweizhang_mcpelauncher_ScriptManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zhuoweizhang_mcpelauncher_ScriptManager
 * Method:    nativeSetTile
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_mcpelauncher_ScriptManager_nativeSetTile
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     net_zhuoweizhang_mcpelauncher_ScriptManager
 * Method:    nativeSetupHooks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_zhuoweizhang_mcpelauncher_ScriptManager_nativeSetupHooks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
