/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zhuoweizhang_pokerface_PokerFace */

#ifndef _Included_net_zhuoweizhang_pokerface_PokerFace
#define _Included_net_zhuoweizhang_pokerface_PokerFace
#ifdef __cplusplus
extern "C" {
#endif
#undef net_zhuoweizhang_pokerface_PokerFace_PROT_READ
#define net_zhuoweizhang_pokerface_PokerFace_PROT_READ 1L
#undef net_zhuoweizhang_pokerface_PokerFace_PROT_WRITE
#define net_zhuoweizhang_pokerface_PokerFace_PROT_WRITE 2L
#undef net_zhuoweizhang_pokerface_PokerFace_PROT_EXEC
#define net_zhuoweizhang_pokerface_PokerFace_PROT_EXEC 4L
#undef net_zhuoweizhang_pokerface_PokerFace_PROT_NONE
#define net_zhuoweizhang_pokerface_PokerFace_PROT_NONE 0L
#undef net_zhuoweizhang_pokerface_PokerFace__SC_PAGESIZE
#define net_zhuoweizhang_pokerface_PokerFace__SC_PAGESIZE 39L
/*
 * Class:     net_zhuoweizhang_pokerface_PokerFace
 * Method:    mprotect
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_net_zhuoweizhang_pokerface_PokerFace_mprotect
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     net_zhuoweizhang_pokerface_PokerFace
 * Method:    sysconf
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_zhuoweizhang_pokerface_PokerFace_sysconf
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
